name: Build and deploy


on:
  push:
    branches: [ main ]
    
    
  workflow_dispatch:
  
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '15.3.0'
      - name: Install dependencies
        run: |
          cd frontend-2
          npm i --legacy-peer-deps
      - name: Run tests
        run: |
          cd frontend-2
          npm run test
      - name: Build dependecies
        run: |
          cd frontend-2
          CI=false npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: frontend-2/build
          
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: frontend-2/build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
        
        
        
    
